### ISSUE TITLE
Updated NOAA api

### ISSUE THREAD

**Issue by gwsHunter** [fitnr/tidetable#1]
Used pip to successfully install tidetable in Python 3.7.

Run the below code:

import tidetable
table = tidetable.get(8416092, year=2019)

and get the below error:

File ... site-packages\tidetable\tidetable.py", line 57, in parse
    prelim = dict(zip(header, re.split(tab, row.decode('ascii'))))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 52: ordinal not in range(128)

**Comment by fitnr** [comment]
This indicates a problem with the data coming in from the NOAA "api". It looks like they have have updated things again. I'll take a look at what needs to change in this library.

**Comment by EdLipson5117** [comment]
Any progress on making the changes to the API to the web service? 
Library installed on 3.10 but sample (and PYPI page links) fails.

**Comment by fitnr** [comment]
I'm unable to reproduce the error, I believe that the disruption with the NOAA api was temporary, not a permanent update.
I've updated the README with slightly adjusted examples.
